### ISSUE TITLE
Needs some kebab-case

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#107]
Too much snake_case. ;-)

**Comment by PeterBowman** [comment]
Kebab was served hot by @rsantos88 at #142. Marking as duplicate of #135, though, and closing.

**Comment by jgvictores** [comment]
> Kebab was served hot by @rsantos88 at #142. Marking as duplicate of #135, though, and closing.

@PeterBowman Best comment con kebab-case ever LOL
