### ISSUE TITLE
Redundant install clause in CMake files

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#112]
It seems that we have redundant install clauses in CMake files that may cause `yarpdev` to crash.

For instance, in `libraries/BodyYarp/Jre/CMakeListst.txt`, [line 19](https://github.com/roboticslab-uc3m/yarp-devices/blob/0967a88a7e00a6f995118f7db57eb4609cc7660a/libraries/BodyYarp/Jr3/CMakeLists.txt#L19): 
```
  install(TARGETS Jr3 DESTINATION lib)
```
Is no longer required due to `yarp_add_plugin`

**Comment by jgvictores** [comment]
It's not only redundant, we've seen these duplicates (lib in `/usr/local/lib` and `/usr/local/lib/yarp`) cause obscure segfaults. Thanks for pointing this out!

**Comment by jgvictores** [comment]
PS: Edited your post just to link to line. ;-)
