### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#128]
Improve examples:
- [x] Fix broken examples
- [x] Import required examples from asibot-main, see https://github.com/roboticslab-uc3m/asibot-main/issues/38
- [x] Example of `IFrameGrabberControls2` based on `GrabberControls2Gui` program from this repo (careful with YARP version).

**Comment by jgvictores** [comment]
Have to be careful with https://github.com/roboticslab-uc3m/yarp-devices/pull/129 \:\-O

**Comment by David-Estevez** [comment]
Let me leave you here what I think could be a good example for the IFrameGrabberControls2 bindings in Python (continued from #140):

```python
#Check for YARP network
yarp.Network.init()
if not yarp.Network.checkNetwork():
    print('Could not connect to YARP network. Please try running YARP server.')
    quit()

# Create and configure driver
options = yarp.Property()
options.put('device','remote_grabber')
options.put('remote', '/grabber')
options.put('local','/GrabberControls2Gui')
dd = yarp.PolyDriver(options)

# View driver as FrameGrabber
controls = dd.viewIFrameGrabberControls2()

# Check if a feature exists
print(controls.hasFeature(yarp.YARP_FEATURE_GAIN))

# Get the current value of a feature
gain = controls.getFeature(yarp.YARP_FEATURE_GAIN)
print(gain)

# Set a new value for a feature
controls.setFeature(yarp.YARP_FEATURE_GAIN, 10)

# Close device and disconnect from the YARP network
dd.close()
yarp.Network.fini()

```

**Comment by jgvictores** [comment]
@David-Estevez Thanks!

**Comment by PeterBowman** [comment]
> Fix broken examples

Reviewed at e0c8394 (not merged yet), all examples compile successfully.

**Edit (2018/01/21):** already merged into `develop`.

**Comment by jgvictores** [comment]
> Import required examples from asibot-main, see roboticslab-uc3m/asibot-main#38

Done at 20531227d19a189acf612aa352833d3ed17ca453

**Comment by jgvictores** [comment]
> Example of IFrameGrabberControls2

Done at 6dcce3b235dab788bda1b3425207b2d55b6cb074
