### ISSUE TITLE
Rename /doc files to kebab-case

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#135]
From [best-practices.md](https://github.com/roboticslab-uc3m/best-practices/blob/9b489338af800beb4cfee4f832da01ec6ba8b2e9/en/best-practices.md):

> The preferred way of naming files in /doc is kebab-case.

- [x] Rename /doc files to kebab-case
- [x] Update any internal (and external!) links that can break.

**Comment by rsantos88** [comment]
done it [here](https://github.com/roboticslab-uc3m/yarp-devices/pull/142)

**Comment by jgvictores** [comment]
@rsantos88 Thanks for moving on with this issue! Please see review comment by @PeterBowman on #142 (was stated above, `Update any internal (and external!) links that can break.`).

**Comment by jgvictores** [comment]
Looks good to me! @rsantos88 Thanks!
