### ISSUE TITLE
Using XWiimote deprecated function

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#138]
To solve #134, 6735632f672ed0da20cdaad33c5460388ae81239 was introduced.
1. If we continue with old distros (see https://github.com/roboticslab-uc3m/teo-main/issues/26 and related), see if we can catch xwii version via preprocessor and `#ifdef`accordingly.
1. If we move on to newer distros on all systems, move on to newer function again.

**Comment by PeterBowman** [comment]
I could either parse the version string from `/usr/lib/x86_64-linux-gnu/pkgconfig/libxwiimote.pc` (not the best idea if the location/format of this file differs from one architecture/OS to another) or start playing with [`try_run()`](https://cmake.org/cmake/help/v3.0/command/try_run.html).

**Edit:** or improve `FindXWiimote.cmake` so that a `XWIIMOTE_VERSION` is set, then either restrict building this component from v2 onwards only or support v0.3 (with the old `xwii_iface_poll`) via preprocessor definition.

**Comment by jgvictores** [comment]
In addition to `priority: low`, added `blocked` by https://github.com/roboticslab-uc3m/teo-main/issues/26 label. BTW, could add `interesting` label too. :smile:

**Comment by PeterBowman** [comment]
I actually gave a try to the pkg-config solution mixed with find modules and seems promising, expect updates soon.

> not the best idea if the location/format of this file differs from one architecture/OS to another

This is not a big deal: `.pc` files should land in some standard location and CMake takes care of the rest with [` pkg_check_modules()`](https://cmake.org/cmake/help/v3.1/module/FindPkgConfig.html).

**Comment by PeterBowman** [comment]
Should be fine at 0eb18f3, closing as done. I'll write down this page here as it explains quite a few useful things about find modules:

https://cmake.org/Wiki/CMake:How_To_Find_Libraries

**Comment by jgvictores** [comment]
> Should be fine at 0eb18f3, closing as done. I'll write down this page here as it explains quite a few useful things about find modules:
>
> https://cmake.org/Wiki/CMake:How_To_Find_Libraries

Cool commit!

Also added the ref to the cmake wiki at https://github.com/asrob-uc3m/tutoriales/blob/master/software/programming/cmake.md

**Comment by PeterBowman** [comment]
Another (and up-to-date) ref on writing nice find modules:

https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#a-sample-find-module

And how `FindXWiimote.cmake` looks now: [link](https://github.com/roboticslab-uc3m/yarp-devices/blob/ba82b176465f84b719a5b1e1fc2fc198af9d472f/cmake/find-modules/FindXWiimote.cmake).

BTW [The Difference Between Deprecated, Depreciated and Obsolete (SO)](https://stackoverflow.com/q/9208091).

**Comment by jgvictores** [comment]
> Another (and up-to-date) ref on writing nice find modules:
> 
> https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#a-sample-find-module

Thanks! Updated [here](https://github.com/asrob-uc3m/tutoriales/commit/1939c0448035938a34df4010602b585f7272c8b9)!
