### ISSUE TITLE
YARP device for RealSense

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#148]
Develop a YARP device for RealSense.  Inherit from `yarp::dev::DeviceDriver`, `yarp::dev::IRGBDSensor`, `yarp::dev::IFrameGrabberControls2`.

**Comment by jgvictores** [comment]
http://yarp.it/devel/classyarp_1_1dev_1_1realsense2Driver.html

**Comment by traversaro** [comment]
As this issue comes quite high in my Google results for "YARP realsense", it may be useful to drop a link to the new repo in which the realsense YARP driver is maintained: https://github.com/robotology/yarp-device-realsense2 .
