### ISSUE TITLE
Support to detect supported features in grabbercontrols2gui

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#149]
I designed `grabbercontrols2gui` to be specific for our GigE camera and its current needs, and hence its old name, `AravisGigEController` and the supported subset of camera features.

Since we want to use this GUI with many devices, some of those specific features might not be present in every grabber, so it would be great to detect which of those features are not available (I'm thinking of zoom, for instance) and disable the corresponding controls.

**Comment by jgvictores** [comment]
Great! Nice follow-up of #147 , perfect labels. :-)
