### ISSUE TITLE
ProximitySensorsClient device is always built despite disabling it via CMake option

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#155]
And therefore it cannot be disabled and it is always compiled.

Easy to fix, but I prefer not to mess up someone else's code. :sweat_smile:

**Comment by PeterBowman** [comment]
My bad, fixed at ae0609c. Thanks for noticing and reporting this!

BTW usual CMake option checks for YARP devices have been removed in favour of the following lines:

https://github.com/roboticslab-uc3m/yarp-devices/blob/ae0609cd39b91c9e8b5b3ebdbfb96f46d2b0e6e5/libraries/YarpPlugins/ProximitySensorsClient/CMakeLists.txt#L4-L8

The code above and `DEFAULT ON` means that *ProximitySensorsClient* shall be always enabled (reminds me of roboticslab-uc3m/QA#18). However, the option is still accessible through `ccmake` and, of course, `cmake path/to/source/ -DENABLE_ProximitySensorsPlugin=OFF` will (now) do the trick.
