### ISSUE TITLE
Derive from concrete YARP classes instead of providing custom implementation

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/yarp-devices#162]
YARP's fakeMotionControl device inherits from several `ImplementX` concrete classes, e.g. `ImplementVelocityControl2`, a ready-to-use implementation of `IVelocityControl2`. See inheritance diagram in [fakeMotionControl's docs](http://www.yarp.it/classyarp_1_1dev_1_1FakeMotionControl.html). I wonder if we could use this in our CAN devices to spare a few lines of code.

**Comment by jgvictores** [comment]
Blocking #171

**Comment by PeterBowman** [comment]
Note to self: take a look at http://www.yarp.it/classyarp_1_1dev_1_1ControlBoardHelper.html (perhaps for internal use only).

**Comment by jgvictores** [comment]
Does not really block #171

**Comment by PeterBowman** [comment]
This WIP led to https://github.com/robotology/yarp/pull/1867, another PR is coming.

**Comment by jgvictores** [comment]
Blocks #171.

**Comment by PeterBowman** [comment]
Might render invalid due to https://github.com/roboticslab-uc3m/yarp-devices/issues/211.

**Comment by PeterBowman** [comment]
For instance, if we take a look at [ImplementControlLimits.h](https://github.com/robotology/yarp/blob/v3.1.1/src/libYARP_dev/include/yarp/dev/ImplementControlLimits.h), there are two interfaces:

* `StubImplControlLimitsRaw`: targets a `Raw` device, provides a stub implementation that prints an error notice and returns `false`. The only place I could use these interfaces is CuiAbsolute, leaving here my abandoned commit for future reference: https://github.com/roboticslab-uc3m/yarp-devices/commit/cc80172b4a56564f63d5aa8cfe85821f56b96ee2. Superseded by https://github.com/roboticslab-uc3m/yarp-devices/issues/211.

* `ImplementControlLimits`: comprises an cpp counterpart ([ImplementControlLimits.cpp](https://github.com/robotology/yarp/blob/v3.1.1/src/libYARP_dev/src/ImplementControlLimits.cpp)) that performs basic mapping and call forwarding to raw devices assuming a correct initialization. Could be implemented in:
  * `FakeControlboard`: probably going to be removed with https://github.com/roboticslab-uc3m/yarp-devices/issues/192.
  * `CanBusControlboard`: currently performs simple routing, but I have a major rework in mind involving CAN reads&writes (https://github.com/roboticslab-uc3m/yarp-devices/issues/209). Would require implementing currently omitted methods in the raw device implementations.

The `CanBusControlboard` thing could be revisited in the future if https://github.com/roboticslab-uc3m/yarp-devices/issues/209 cannot be done. Closing for now as WONTFIX.
