### ISSUE TITLE
torque mode is not working with launchLocomotion

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#166]
Following the tricks [here](https://github.com/roboticslab-uc3m/yarp-devices/blob/bcdb7d7d324790c0cf1a1047ce1e3d20c659eab1/doc/juan-tricks.md), it doesn't work.
```bash
>>[set] [trqd]
Response: [fail]
```
The other commands are working well:
```bash
>>[get] [icmd] [cmds]
Response: [is] [cmds] ([pos] [pos] [pos] [pos] [pos] [pos]) [tsta] 3 1517832094.68717 [ok]
>>[get] [llim]
Response: [is] [llim] -90.0 90.0 [tsta] 4 1517832104.60817 [ok]
>>[get] [llim] 1
Response: [is] [llim] -20.0 20.0 [tsta] 5 1517832109.48228 [ok]
>>[get] [llim] 2
Response: [is] [llim] -30.0 45.0 [tsta] 6 1517832112.8324 [ok]
```

**Comment by rsantos88** [comment]
blocking https://github.com/roboticslab-uc3m/teo-main/issues/15

**Comment by PeterBowman** [comment]
The `[trqd]` command (and `[veld]`) was removed, try `set icmd cmod 0 torq`.

**Comment by jgvictores** [comment]
Tricks are unstable hacks. Best to use bindings, see and improve https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/example/python/exampleRemoteControlboard.py

**Comment by rsantos88** [comment]
Ok! `set icmd cmod 0 torq` works perfectly.
The updated command is [here](https://github.com/roboticslab-uc3m/yarp-devices/blob/develop/doc/yarp-devices-tricks.md#yarp-rpc-commands-vocabs)
Thanks @PeterBowman @jgvictores
