### ISSUE TITLE
unavailable computers running services on YMM

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#173]
When we try to use the services of `teoBase_app` running through `YARP module manager`, the computers of TEO are unavailables. 
Note: I've tried this [trick](http://robots.uc3m.es/index.php/TEO_Network_troubleshooting) but it doesn't work.
Yarp version instaled on TEO computers: `2.3.70.2`
Yarp version instaled on client computer: `2.3.72`

**Comment by PeterBowman** [comment]
Can these computers see each other through YARP, that is, is the usual `yarp conf` + `yarp detect` step successful?

BTW this issue probably belongs to teo-hardware-issues/teo-developer-manual/teo-main.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-main#43
