### ISSUE TITLE
Develop serial Dextra device

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#176]
WIP at https://github.com/roboticslab-uc3m/yarp-devices/compare/issue-176-dextra

**Edit (2019/06/28):** two different device implementations will coexist at some point per https://github.com/roboticslab-uc3m/yarp-devices/issues/176#issuecomment-449354375. This issue focuses on the USB-related stuff, the CAN implementation depends on other tasks (e.g. PCB design, hardware, etc.).

**Comment by jgvictores** [comment]
Should match firmware at https://github.com/jgagom/Dextra

**Comment by jgvictores** [comment]
Client protocol explicit in https://github.com/jgagom/Dextra/blob/master/Control/DextraControl.py ( https://github.com/Alvipe/Dextra/blob/33203e128c3d3c4292f41d32275cb336cd211733/Control/DextraControl.py )

**Comment by jgvictores** [comment]
May work. Relevant changes: https://github.com/roboticslab-uc3m/yarp-devices/compare/400ea3d...4b85d31

**Comment by jgvictores** [comment]
Blocks #171.

**Comment by jgvictores** [comment]
On a side note, planning on moving the current USB implementation. Tracked at https://github.com/roboticslab-uc3m/sign-language-papers/issues/5 (private and subject to name change; name changes are documented [here](https://github.com/roboticslab-uc3m/developer-manual/blob/master/frequently-asked-questions.md#ive-found-some-broken-links-in-your-repositories-which-have-been-renamed) ([perma](https://github.com/roboticslab-uc3m/developer-manual/blob/6bff430bdf0b862211aa7944e053efdbabe15191/frequently-asked-questions.md#ive-found-some-broken-links-in-your-repositories-which-have-been-renamed) and the upcoming ones are tracked at "Organize research-oriented repos https://github.com/roboticslab-uc3m/questions-and-answers/issues/75").

**Comment by PeterBowman** [comment]
> WIP at https://github.com/roboticslab-uc3m/yarp-devices/compare/issue-176-dextra

Merged into develop at https://github.com/roboticslab-uc3m/yarp-devices/commit/11a1b22ed664febbbd2edd98266f701e112e3143, updated title and description of this issue. Current status:

* DextraControlboardUSB (renamed from DextraControlboard): not sure if working, could be improved upon in this repo or moved somewhere else.
* DextraControlboard (CAN comms): TO-DO, we'll be focusing on that in this issue from now on.

**Comment by PeterBowman** [comment]
Let's do https://github.com/roboticslab-uc3m/yarp-devices/issues/171 first.

**Comment by PeterBowman** [comment]
> TO-DO, we'll be focusing on that in this issue from now on.

Sorry, switching back (and actually stating this explicitly in the title) to USB device per the original intent. We are not yet close to developing the CAN device, the USB one needs polishing.

**Comment by PeterBowman** [comment]
@jgvictores OK to rename DextraControlboardUSB to DextraSerialControlboard? Future CAN device would be DextraCanBusControlboard or so.

**Comment by PeterBowman** [comment]
> @jgvictores OK to rename DextraControlboardUSB to DextraSerialControlboard? Future CAN device would be DextraCanBusControlboard or so.

Seemed uncontroversial to me. Done and ready for review at https://github.com/roboticslab-uc3m/yarp-devices/pull/216.
