### ISSUE TITLE
Install yarp  (Debian 6.0)

### ISSUE THREAD

**Issue by edwinDOS** [roboticslab-uc3m/yarp-devices#18]
typed:

`cmake .. -DCREATE_LIB_MATH=ON -DCREATE_GUIS=ON -DCREATE_OPTIONAL_CARRIERS=ON -DENABLE_yarpcar_mjpeg_carrier=ON`

Appears the following CMake error:

`CMake Error at CMakeList.txt:5 (cmake_minimun_required):
     CMake 2.8.9 or higher is required. You are running version 2.8.2
`

**Comment by jgvictores** [comment]
Okay, I've updated http://robots.uc3m.es/dox-teo-body/teo_body_install_cmake_on_debian_6.html to reflect the need for activating backports. First you have to add:

  deb http://backports.debian.org/debian-backports/ squeeze-backports main

to your /etc/apt/sources.list file, apt-get update and then install the cmake packages from the backports repository following the instructions. This is similar to this old YARP thread: http://sourceforge.net/p/robotcub/mailman/robotcub-hackers/?viewmonth=201306&viewday=4
