### ISSUE TITLE
[cmake] Not seeing or compiling dumpCanBus nor checkCanBus

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#183]
[cmake] Not seeing or compiling dumpCanBus nor checkCanBus

**Comment by PeterBowman** [comment]
Thanks for reporting. My bad, I deleted the `ENABLE_YarpPlugins` CMake option at https://github.com/roboticslab-uc3m/yarp-devices/commit/832514c338caf8a22bb94b976e0bd0ed0548e96e#diff-ad8e103b0ccf2615d0164a708c6dc55e, but forgot to remove its dependers (*checkCanBus*, *dumpCanBus* and unit tests), too.
