### ISSUE TITLE
Export "Edit .ini config files in Calc (Excel)"

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#196]
Export [Edit .ini config files in Calc (Excel)](https://github.com/roboticslab-uc3m/yarp-devices/blob/e696c219fa9aa6203d008585123ea477d9b74454/doc/yarp-devices-tricks.md#edit-ini-config-files-in-calc-excel), probably to https://github.com/roboticslab-uc3m/developer-manual

Blocked by https://github.com/roboticslab-uc3m/questions-and-answers/issues/63

**Comment by PeterBowman** [comment]
Mercilessly nuked by @jgvictores at https://github.com/roboticslab-uc3m/yarp-devices/commit/db1988243cb50c440c86359911a30572b935686f, this section lives now at developer-manual (https://github.com/roboticslab-uc3m/developer-manual/commit/9c11c75d4ef5de8ac43a90ab3184fdf8e85a3290).
