### ISSUE TITLE
Implementing new functions of JR3 sensors

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#200]
In order to obtain the values of the sensors correctly and calibrate them, resetting all or each one of the channels that we want to 0, the [calibrateSensor()](https://github.com/roboticslab-uc3m/yarp-devices/blob/jr3-improvement/libraries/YarpPlugins/Jr3/IAnalogSensorImpl.cpp#L78-L88) and [calibrateChannel(int ch)](https://github.com/roboticslab-uc3m/yarp-devices/blob/jr3-improvement/libraries/YarpPlugins/Jr3/IAnalogSensorImpl.cpp#L99-L122) functions have been implemented. In addition, a test example has been added to check these functions [here](https://github.com/roboticslab-uc3m/yarp-devices/blob/jr3-improvement/examples/cpp/exampleRemoteJr3-2/exampleRemoteJr3-2.cpp)
It works well. if you don't see anything strange, we can do a [PR](https://github.com/roboticslab-uc3m/yarp-devices/pull/199)

**Comment by PeterBowman** [comment]
Closed in #199.
