### ISSUE TITLE
[playbackServer] requires a state machine

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#21]
Consider use of https://github.com/asrob-uc3m/robotDevastation/tree/gameFSM/src/libraries/StateMachineLib.

**Comment by David-Estevez** [comment]
@jgvictores I can add extra documentation for the gameFSM lib in case you need it

**Comment by jgvictores** [comment]
The `PlaybackThread`class described in #22 implements its own state machine.
