### ISSUE TITLE
[TechnosoftIpos] Check encoder wires before enable

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#23]
Possible software check encoder wires **before** enable... ?

**Comment by rsantos88** [comment]
I think that now can be used checkCanBus program for this task if you want to check Cui absolute encoders. See (#56)

**Comment by jgvictores** [comment]
Yes, this is good. The issue itself was just citing explicitly a specific feature that could be included in #27 or #2.
Closing this issue as this check and much more has been done in https://github.com/roboticslab-uc3m/teo-body/pull/56 (that actually closed #27).
