### ISSUE TITLE
Migrate Jr3 to use YARP Multiple Analog Sensor Interfaces

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#240]
See http://www.yarp.it/group__dev__iface__multiple__analog.html and [robotology/yarp#1526](https://github.com/robotology/yarp/issues/1526) .

Note: Issue involves updating
1. https://github.com/roboticslab-uc3m/teo-configuration-files as described in https://github.com/roboticslab-uc3m/teo-configuration-files/issues/27
2. https://github.com/roboticslab-uc3m/installation-guides/blob/695512226b313079aa83307611c7a25e0263a928/install-jr3.md#view-jr3-data
3. https://github.com/roboticslab-uc3m/yarp-devices/tree/master/examples

**Comment by PeterBowman** [comment]
The `ISixAxisForceTorqueSensors` interface has been implemented at https://github.com/roboticslab-uc3m/yarp-devices/commit/2475bb1f25c45f9b19b0ea27daf4d01bdb81a726 while still preserving `IAnalogSensor` (mapping calls between implementations to avoid code duplication). The device can be still instantiated as an `analogServer`'s subdevice (as usual, via `yarpdev --device Jr3`), but now it can be also wrapped by the new MAS in this way:

`yarpdev --device multipleanalogsensorsserver --subdevice Jr3 --name /jr3 --period 20`

I guess we need to wait for YARP devs to learn whether they decide to keep or nuke `analogServer`.

Note that `IAnalogSensors` is still used in our examples: [exampleJr3.cpp](https://github.com/roboticslab-uc3m/yarp-devices/blob/b70e1377d043cfbc165eb6aacaa91473f2625617/examples/cpp/exampleJr3/exampleJr3.cpp), [exampleRemoteJr3.cpp](https://github.com/roboticslab-uc3m/yarp-devices/blob/b70e1377d043cfbc165eb6aacaa91473f2625617/examples/cpp/exampleRemoteJr3/exampleRemoteJr3.cpp), [exampleRemoteJr3.py](https://github.com/roboticslab-uc3m/yarp-devices/blob/b70e1377d043cfbc165eb6aacaa91473f2625617/examples/python/exampleRemoteJr3.py).

**Comment by PeterBowman** [comment]
The new [ftCompensation app](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/ff5092ac0fd0d9fc4bbe40f2d4678eb4d0d7bf6d/programs/ftCompensation) uses this MAS implementation of Jr3: https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/191.

**Comment by PeterBowman** [comment]
Our local C++/Python examples have been migrated to using the new MAS interface: https://github.com/roboticslab-uc3m/yarp-devices/commit/de914de92fd227d9675b03a132b15e769bf26bbf. Keep in mind there is no calibration (set-to-zero) method, therefore either restart the device or apply an offset programatically to achieve that.
