### ISSUE TITLE
[dumpCanBus] It does not output canBus messages if you use the"build-clean" version

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#29]
When you start the program, it says:
|| clearing context
||| adding context [dumpCanBus]
||| configuring
||| no policy found
||| default config file specified as dumpCanBus.ini
||| checking [/home/teo/git/teo-body/build-clean/bin/dumpCanBus.ini](pwd)
||| checking [/home/teo/.config/yarp/robots/default](robot YARP_CONFIG_HOME)
||| checking [/home/teo/.local/share/yarp/robots/default](robot YARP_DATA_HOME)
||| checking [/etc/yarp/robots/default](robot YARP_CONFIG_DIRS)
||| checking [/home/teo/teo-body/build/share/teo-body/robots/default](robot YARP_DATA_DIRS)
||| checking [/home/teo/teo-main/build/share/teo/robots/default](robot YARP_DATA_DIRS)
||| checking [/home/teo/teo-body/build/share/teo-body/config/path.d](robot path.d YARP_DATA_DIRS)
||| checking [/home/teo/teo-main/build/share/teo/config/path.d](robot path.d YARP_DATA_DIRS)
||| checking [/home/teo/.config/yarp/contexts/dumpCanBus](context YARP_CONFIG_HOME)
||| checking [/home/teo/.local/share/yarp/contexts/dumpCanBus](context YARP_DATA_HOME)
||| checking [/etc/yarp/contexts/dumpCanBus](context YARP_CONFIG_DIRS)
||| checking [/home/teo/teo-body/build/share/teo-body/contexts/dumpCanBus](context YARP_DATA_DIRS)
||| found /home/teo/teo-body/build/share/teo-body/contexts/dumpCanBus
||| checking [/home/teo/teo-main/build/share/teo/contexts/dumpCanBus](context YARP_DATA_DIRS)
||| checking [/home/teo/teo-body/build/share/teo-body/contexts/dumpCanBus/dumpCanBus.ini](context)
||| found /home/teo/teo-body/build/share/teo-body/contexts/dumpCanBus/dumpCanBus.ini
[INFO]created device <CanBusHico>. See C++ class teo::CanBusHico for documentation.

**Comment by jgvictores** [comment]
Can bus messages in dumpCanBus are output using CD_SUCCESS.
ColorDebug_HIDE_SUCCESS is a CMake option that propagates through the build of the whole project.
If this option is set in your build-clean directory, no output will be given by dumpCanBus. If you want to see the output again, please recompile your build-clean directory with ColorDebug_HIDE_SUCCESS OFF (in ccmake ..).
