### ISSUE TITLE
Error with yarp starting launchManipulation

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#30]
When we connect with teo@manipulation and we start launchManipulation, it sais:
[info] main.cpp:58 main(): Checking for yarp network...
[error] main.cpp:61 main(): Found no yarp network (try running "yarpserver &"), bye!

**Comment by jgvictores** [comment]
Fixed by making sure there are no yarp servers on teo@manipulation, and running:
`yarp detect --write`
at teo@manipulation.
