### ISSUE TITLE
[oneCanBusOneWrapper] Segmentation fault

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#31]
When I run OneCanBusOneWrapper with oneCanBusOneWrapper.ini configurated with canDevice /dev/can1, the program works correctly but after some time... it shows Segmentation fault.

**Comment by jgvictores** [comment]
Checked it, happened in less than 3 s, was in init.
Fixed by recompiling teo-body (forgot to do it after upgrading YARP for https://github.com/j-lorente/TEO_push/issues/1).
