### ISSUE TITLE
Define the scope of the repository

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#32]
I have seen some commits lately for the "waiter" application on this repo, and I was wondering if we should keep this repo just for generic functionalities (drivers o modules that can be used in several different applications) and create new repositories for specific applications.

What do you think, guys?

(See also: [teo-head - issue11](https://github.com/roboticslab-uc3m/teo-head/issues/11) )

**Comment by David-Estevez** [comment]
I guess it is now clear that this repo is related only to robot-related code and not application-related code.

**Comment by PeterBowman** [comment]
This repo might be slightly repurposed to hold a collection of sensor/actuator YARP devices in the near future (that is, expanding current CAN and jr3 devices + tts/asr from teo-head). See roboticslab-uc3m/QA#2.

**Comment by David-Estevez** [comment]
I didn't know...Thanks, @PeterBowman !! :smile: :+1:
