### ISSUE TITLE
Add blinking lights

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/yarp-devices#36]
As the TV reporters always say, blinking lights make the robot cooler.

**Comment by jgvictores** [comment]
@David-Estevez We'll report this ASAP at the next ASROB meeting. The (rd)-research LED matrix know-how may be reusable. It would be a pity for such a feature to go AWOL.

**Comment by David-Estevez** [comment]
(Migrated to https://github.com/roboticslab-uc3m/teo-hardware-manual/issues/6)
