### ISSUE TITLE
Avoid "using namespace"

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#40]
I think, we can add the some solution of Teo-Head  for resolve possible conflicts with namespaces that may appear in the future. Can someone resolve it??

**Comment by rsantos88** [comment]
Ok, now there are not “using namespace” in teo-body proyect and the code compiles perfectly (4b931232a1f4b785993cd7b179a066e09b0deac4)

**Comment by jgvictores** [comment]
Closed at https://github.com/roboticslab-uc3m/teo-body/pull/41.
