### ISSUE TITLE
Detecting absolute encoders when failing in launchManipulation or launchLocomotion

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/yarp-devices#42]
Now, when I start launchManipulation or launchLocomotion, the application will realize a tests of all absolute encoders. If all is right, it runs perfectly but if one or some encoders fail, it will show this message: 
`[info] ICanBusSharerImpl.cpp:31 setIEncodersTimedRawExternal(): Wait to get external encoder value.`
Does the application could show which IDs encoders are failing at this time? It can be useful to detect the problem without using dumpCanBus.

**Comment by jgvictores** [comment]
Commited at 140ec25012b64a292cc746592259db48d140556a. Please test and close issue if OK !!

**Comment by rsantos88** [comment]
Ok. Now it works perfectly.
Thanks
