### ISSUE TITLE
Create image and partition of working manipulation and locomotion OSs

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#43]
Crear una imagen de los discos duros (backup) y una partición arrancable en los PCs de manipulación y locomoción:
- [x] Crear imagen (copia de seguridad de manipulation, locomotion y head) con FSArchiver y subir .fsa a http://robots.uc3m.es/svn/TEOrepo/backups/.
- [x] Reducir partición actual a un tamaño propicio para realizar un backup
- [x] Crear la nueva partición para el backup
- [x] Utilizar la herramienta FSArchiver para crear una partición (backup) arrancable
- [x] Instalar Ubuntu 14.04 en teo-head

**Comment by rsantos88** [comment]
Ya se ha realizado el Backup de los 3 PCs y se han subido los ficheros .fsa a http://robots.uc3m.es/svn/TEOrepo/backups/.

**Comment by rsantos88** [comment]
Se ha reducido la partición actual de los PCs: manipulation y locomotion a aproximadamente 90 GB (87,69 GB), creando una nueva partición adicional de aproximadamente 20 GB (19,53 GB) con formato ext3. De la misma manera, la partición principal de PC Head se ha reducido la partición a 35,74 GB (debido a que el disco duro tiene la mitad de tamaño que los anteriores), creando también una partición adicional de aproximadamente 20GB (19.53 GB) y formato ext4.

**Comment by rsantos88** [comment]
**IMPORTANTE:** Se están realizando cambios en el ordenador de manipulación para poder crear una segunda partición arrancable por lo que se ruega no guardar datos importantes en este ordenador sin tener previamente una copia de seguridad. El backup del mismo en caso de pérdida de datos se ha realizado el 22/04/2016.

**Comment by rsantos88** [comment]
Ya está realizado el backup de todos los discos de los PCs: _teo-head_, _manipulation_, y _locomotion_. Se han clonado particiones principales a una partición secundaria de aproximadamente 20GB arrancable que podremos seleccionar desde el menú de Grub con nombre "_Linux.....(Backup: 22/04/2016)_ " situada en la parte inferior de la lista de Grub. El procedimiento de como restaurar la imagen del sistema operativo (backup) se encuentra documentada en la wiki: [Tutorial](http://robots.uc3m.es/index.php/Tutorial:_C%C3%B3mo_restaurar_un_S.O_en_una_partici%C3%B3n_arrancable)

**Comment by rsantos88** [comment]
Tal y como he hablado con @jgvictores , se va a instalar en `teo-head`  también una partición limpia con Ubuntu 14.04.

**Comment by jgvictores** [comment]
THANKS!!!

**Comment by rsantos88** [comment]
Instalado Ubuntu 14.04 LTS en `teo-head`. Instalado software para cabeza en la nueva distribución. Funcionando :+1:

**Comment by jgvictores** [comment]
Thanks a LOT!!!! :+1:
