### ISSUE TITLE
[TechnosoftIpos] Timeout if no absolute encoder message is received

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#44]
Implement timeout in [TechnosoftIpos] if no absolute encoder message is received, for instance displaying an error message and then continue by defaulting to using relative encoders.

**Comment by jgvictores** [comment]
Implement only on forcing timeout through --externalEncoderWait [s] parameter.

**Comment by rsantos88** [comment]
Implemented in #77. 
Now, if you for run launchManipulation or launchLocomotion and you see for example a error message, like:
`Cui Absolute (PIC ID: 120) doesn't respond. Try using --externalEncoderWait [seconds] parameter with timeout higher than 0` 
the Absolute Encoder doesn't respond, so use --externalEncoderWait [seconds] parameter for using default relative encoder position.
