### ISSUE TITLE
[TechnosoftIpos] Update vocabs to be yarpmotorgui compatible

### ISSUE THREAD

**Issue by munozyanez** [roboticslab-uc3m/yarp-devices#46]
Update vocabs to be yarpmotorgui compatible in:
Starting at https://github.com/roboticslab-uc3m/teo-body/blob/7d44548cbba0d171ba8eb6ceecaad70959ac521a/libraries/BodyYarp/TechnosoftIpos/ICanBusSharerImpl.cpp#L249
Replace VOCABS as in https://github.com/roboticslab-uc3m/teo-main/commit/34ceb96acc72a4a40dcbbb37e63c009863179b34

**Comment by jgvictores** [comment]
Done at 1e5cf491c7c743c622bcdf632ef401525d09cde7 (must install on robot PCs).
