### ISSUE TITLE
yarpmotorgui fails at getting joint limits

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#47]
yarpmotorgui-qt (update: same with yarpmotorgui-gtk) not getting robot joint limits. https://github.com/robotology/yarp/blob/eed2a0afaddf3806a7eb551262c2b8a2f3ea6d08/src/yarpmotorgui-qt/partitem.cpp#L180 gets a false return. Same happens on teo-main/programs/teoSim.

**Comment by jgvictores** [comment]
As pointed out by @PeterBowman we need to implement yarp::dev::IControlLimits2

@rsantos88 Could you do this on CanBusControlboard and TechnosoftIpos?

This would be a great improvement!!

**Comment by jgvictores** [comment]
Fixed at 6328dd5ce4f451b172a6fe176a226e42b463d212

@PeterBowman Thanks again for pointing out the fact that we needed to implement yarp::dev::IControlLimits2 !

**Comment by PeterBowman** [comment]
@jgvictores we've just tested these changes on ASIBOT with yarpmotorgui and it works like a charm, thanks!

**Comment by jgvictores** [comment]
@PeterBowman Great, cool!
