### ISSUE TITLE
QtCreator in Locomotion PC

### ISSUE THREAD

**Issue by lpinel** [roboticslab-uc3m/yarp-devices#49]
I tried to install qtcreator in the LOCOMOTION pc, but failed. Please, can anybody help?
`$ sudo apt-get install qtcreator
...
Failed to fetch http://ftp.es.debian.org/debian/pool/main/q/qtcreator/qtcreator-doc_1.3.1-3_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

$ sudo apt-get update
E: Some index files failed to download, they have been ignored, or old ones used instead.
`
Thanks

**Comment by jgvictores** [comment]
First step has been `sudo cp /etc/apt/sources.list /etc/apt/sources.list.obsolete` and `sudo sed -i "s/ftp.es/archive/g" /etc/apt/sources.list`.
Still issues, due to backports and security.

**Comment by jgvictores** [comment]
Commented out everything except:

```
deb http://archive.debian.org/debian/ squeeze main non-free contrib
deb-src http://archive.debian.org/debian/ squeeze main non-free contrib
```

Was able to install meld, now installing qtcreator.
