### ISSUE TITLE
Velocity control fails in hip (joint 14)

### ISSUE THREAD

**Issue by j-lorente** [roboticslab-uc3m/yarp-devices#50]
Joint 14 of TEO can be moved with position control but not with velocity control.

Velocity control works fine for other joints.

**Comment by j-lorente** [comment]
Please, don't use TEO's hip by now, Santi is looking for the problem with the velocity control.

**Comment by j-lorente** [comment]
We checked the driver's configuration and the problem is not there so it must be in a higher level, in the software.

**Comment by jgvictores** [comment]
I'd recommend trying with oneCanBusOneWrapper, best if you physically disconnect the rest of the CAN nodes.

**Comment by j-lorente** [comment]
Using oneCanBusOneWrapper the joint can be moved with velocity control, so we conclude that the other driver in the hip, which is broken, is probably causing problems.

Then we configured the .ini for ignoring this broken driver and physically took it out, but we still can't move the joint in velocity mode with launchLocomotion.

**Comment by jgvictores** [comment]
For the launchLocomotion .ini file, to preserve the wrapper numbering, I'd recommend simply replacing the "TechnosoftIpos" string for "FakeJoint" in the position corresponding to the faulty driver.

**Comment by smcdiaz** [comment]
New driver arrived last week. Please keep the .ini as is, without modifications. Raul can change the broken driver for the new one

**Comment by rsantos88** [comment]
Now, there are three files .ini in teo-body PC located at “/repos/teo-body/share/launchLocomotion/conf” with the following names: "launchLocomotion.ini"  "launchLocomotion_without_113_114.ini"  "launchLocomotion_without_13_113_114.ini" for testing launchLocomotion with --from parameter.

**Comment by j-lorente** [comment]
We changed and configured driver 14 and we were able to move joint 14 in velocity mode using the Technosoft program.

We tried using launchLocomotion (both ignoring and not ignoring driver 13) and still doesn't work.

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-hardware-issues#25
