### ISSUE TITLE
GIT error: server certificate verification failed 

### ISSUE THREAD

**Issue by lpinel** [roboticslab-uc3m/yarp-devices#55]
I tried to pull, push... and later clone a git repository on locomotion PC and something went wrong. :'(

error: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none while accessing https://github.com/roboticslab-uc3m/project-generator.git/info/refs

fatal: HTTP request failed

**Comment by lpinel** [comment]
I tried : 
 git config --global http.sslverify false (via http://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c)

and it worked, but don't know if it is the best way

**Comment by jgvictores** [comment]
Seems like we'll be living dangerously for a while.

BTW, just accessing https://github.com/roboticslab-uc3m/project-generator.git/info/refs through a web browser returns: `Please upgrade your git client.
GitHub.com no longer supports git over dumb-http:` https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days`

Closing issue as git is functional again.
