### ISSUE TITLE
[CuiAbsolute] Documentación

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#60]
- [x] Correspondencia IDs y valores en código fuente
- [x] Enlazar URL máquina virtual con entorno MPLAB para programación de PICs de CuiAbsolute

**Comment by rsantos88** [comment]
1) http://robots.uc3m.es/index.php/CuiAbsolute_Documentation
2) https://drive.google.com/a/uc3m.es/folderview?id=0BxR76I90oKSmdnRhQlpsS3pXWm8&usp=sharing

**Comment by jgvictores** [comment]
Good! Linked from http://robots.uc3m.es/index.php/TEO
