### ISSUE TITLE
Request of the simulation module of Teo body.

### ISSUE THREAD

**Issue by serna92** [roboticslab-uc3m/yarp-devices#64]
Hello,

I'm a student of the university Carlos III (Leganes) and I'm working in a project related with the robot Asibot which i need to do a simulation using OpenRave. I found that the module jmc_rave is now out of date in Asibot so I would like to ask if you could send the module used to simulate Teo body. Also, I would like to receive a tutorial or documentation about how to set it up in Ubuntu Trusty 14.04.

Thanks in advance and I look forward to your reply.

**Comment by jgvictores** [comment]
Hi @serna92,
For TEO simulations we currently use teoSim, part of https://github.com/roboticslab-uc3m/teo-main
Here's a link to the documentation http://robots.uc3m.es/dox-teo-main/ (install should be the same for Ubuntu 14.04 and 14.10; if not, just put an issue in the teo-main repository).
