### ISSUE TITLE
Error while trying to execute MORSE's YARP example

### ISSUE THREAD

**Issue by ivansolano** [roboticslab-uc3m/yarp-devices#65]
After install MORSE as explained in [MORSE wepbpage](https://www.openrobots.org/morse/doc/latest/user/installation/mw/yarp.html) and install YARP manually as explained [here](https://www.openrobots.org/morse/doc/latest/user/installation/mw/yarp.html). I've tried to execute [this](https://www.openrobots.org/morse/doc/latest/user/beginner_tutorials/yarp_tutorial.html) example of MORSE using YARP but i get the the next error:

> [SCENE INITIALIZATION]
> [    0.159] Component: 'atrv.motion' using datastream 'morse.middleware.yarp_datastream.YarpDatastreamManager'
> [helpers.loading] Module not found: dynamic module does not define init function (PyInit__yarp)
> [helpers.loading] Could not load the class YarpDatastreamManager in morse.middleware.yarp_datastream
> [helpers.loading] Could not create an instance of morse.middleware.yarp_datastream.YarpDatastreamManager
> INITIALIZATION ERROR: Datastream 'morse.middleware.yarp_datastream.YarpDatastreamManager' module could not be found! 
>  Could not import modules required for the desired datastream interface. Check that they can be found inside your PYTHONPATH variable.
> Python script error - object 'Scene_Script_Holder', controller 'Initialize':
> [ERROR][MORSE] Uncaught exception, quit Blender.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3/dist-packages/morse/blender/main.py", line 597, in init
>     init_ok = init_ok and link_datastreams()
>   File "/usr/local/lib/python3/dist-packages/morse/blender/main.py", line 368, in link_datastreams
>     datastream_instance.register_component(component_name, instance, datastream_data)
> AttributeError: 'NoneType' object has no attribute 'register_component'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3/dist-packages/morse/blender/main.py", line 597, in init
>     init_ok = init_ok and link_datastreams()
>   File "/usr/local/lib/python3/dist-packages/morse/blender/main.py", line 368, in link_datastreams
>     datastream_instance.register_component(component_name, instance, datastream_data)
> AttributeError: 'NoneType' object has no attribute 'register_component'

I found the files that contain the module missing and added them to the Pythonpath but the example still doesn't work.

**Comment by jgvictores** [comment]
Closing, as this is not a teo-body issue.

I'd recommend looking at [morse's recommended channels](http://www.openrobots.org/morse/doc/stable/morse.html), such as [their mailing-list](https://sympa.laas.fr/sympa/subscribe/morse-users) or [their bug-tracker](https://github.com/laas/morse/issues).
