### ISSUE TITLE
Outdated "threadrate" parameter breaks on YARP 2.3.66.1

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/yarp-devices#84]
From [yarp/releases/tag/v2.3.66.1](https://github.com/robotology/yarp/releases/tag/v2.3.66.1):

> The `controlboardwrapper2` device (implemented in `yarp::dev::ControlBoardWrapper` has removed the supported for the `threadrate` parameter, that has been deprecated since 2014. Invalid configuration files of the form `threadrate 10` can be update with the valid form `period 10`.

Several .ini files have to be updated.

**Comment by PeterBowman** [comment]
@jgvictores this might actually be worth a cherry pick to master.

**Comment by jgvictores** [comment]
@PeterBowman I really never understood what you meant with that last comment :smile: ...to what do you refer? Something like we should check this among all repos? Or just the fact that keeping up with dependencies can be really tedious in general?

**Comment by PeterBowman** [comment]
@jgvictores a [cherry pick](https://git-scm.com/docs/git-cherry-pick) is basically a copy-paste of one or more commits from one branch to another (your IDE of choice should have such a GUI option). Since `master` branch is currently broken for YARP >2.3.66.1 installations, I referred to applying 1e45ba3 there, too.

**Comment by jgvictores** [comment]
Mmmm ended up doing a `git cherry-pick --abort`, wasn't very fast-forward... ended up doing a brute-force update of master to develop, sorry! :smile:
