### ISSUE TITLE
Implement IPositionControl2 on CanBusControlboard

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#90]
Implement IPositionControl2 on CanBusControlboard and probably down through the whole stack (TechnosoftIpos, etc) to benefit more from `yarpmotorgui` (for instance, not currently showing joint reference velocities).

**Comment by rsantos88** [comment]
Is this what you want?? #92  :confused:

**Comment by jgvictores** [comment]
Commented on #92 :smile:

**Comment by rsantos88** [comment]
migrated to [Yarpmotorgui control modes #2](https://github.com/roboticslab-uc3m/teo-software-manual/issues/2)
