### ISSUE TITLE
Imminent repo name change (teo-body -> yarp-devices)

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/yarp-devices#99]
On Friday March 3rd 2017 evening, this repo will be renamed: teo-body -> yarp-devices

Cheers!

**Comment by jgvictores** [comment]
PS: This is the main reason why we've been migrating teo hardware issues to https://github.com/roboticslab-uc3m/teo-hardware-manual

**Comment by PeterBowman** [comment]
Renaming done. All references to the old location should redirect now to `yarp-devices`, including fetch/push operations. In order to update your remotes, see [Changing a remote's URL](https://help.github.com/articles/changing-a-remote-s-url/). I'd leave this issue open until every single reference in the organization has been updated accordingly: [search](https://github.com/search?q=org%3Aroboticslab-uc3m+teo-body&type=Code).

**Comment by jgvictores** [comment]
Thanks for doing that! 

Btw, edited a typo in your post, from yarp-plugins to the final yarp-devices. 😀

**Comment by jgvictores** [comment]
cc https://github.com/roboticslab-uc3m/QA/issues/2

**Comment by PeterBowman** [comment]
I've tracked down and replaced all occurrences of `teo-body` in the repos at our org, only these are left:

* ~~[waiter/programs/waiterExecutionCore/CMakeLists.txt.user#L62](https://github.com/roboticslab-uc3m/waiter/blob/beea9ad/programs/waiterExecutionCore/CMakeLists.txt.user#L62)~~ (temp file, ignore this)
* follow-me/doc/fig/editable/follow-me-app.graphml:
  * [line 389](https://github.com/roboticslab-uc3m/follow-me/blob/c1ba54c/doc/fig/editable/follow-me-app.graphml#L389) (roboticslab-uc3m/follow-me#36)
  * [line 405](https://github.com/roboticslab-uc3m/follow-me/blob/c1ba54c/doc/fig/editable/follow-me-app.graphml#L405) (roboticslab-uc3m/follow-me#36)
* [teo-software-manual/appendix/b-teo-network-information.md](https://github.com/roboticslab-uc3m/teo-software-manual/blob/8789d4c4975bd5d00748ee1227ecb3b04851b5a3/appendix/b-teo-network-information.md) (roboticslab-uc3m/teo-software-manual#24)

The wiki has been updated, too. Leftovers:
* [Procedimiento Revisión Drivers](http://robots.uc3m.es/index.php/Procedimiento_Revisi%C3%B3n_Drivers) (orphaned, roboticslab-uc3m/teo-software-manual#25)
* TEO Network information:
  * ~~[#manipulation (robot front right PC)](http://robots.uc3m.es/index.php/TEO_Network_information#manipulation_.28robot_front_right_PC.29)~~ (migrated to GitHub)
  * ~~[#locomotion (robot front left PC)](http://robots.uc3m.es/index.php/TEO_Network_information#locomotion_.28robot_front_left_PC.29)~~ (migrated to GitHub)

**Edit:** external services linked to this repo (Travis CI, Coveralls) were synced as well.
  
**Edit2 (2018/01/05):** update.

**Comment by jgvictores** [comment]
Changing priority to high, we should check and replace these occurrences.

**Comment by PeterBowman** [comment]
According to my updated comment (https://github.com/roboticslab-uc3m/yarp-devices/issues/99#issuecomment-284267709), the only things left to do here are tracked at:

* roboticslab-uc3m/follow-me#36.
* roboticslab-uc3m/teo-software-manual#24
* roboticslab-uc3m/teo-software-manual#25

**Comment by jgvictores** [comment]
Can close, because tracked elsewhere, right?
